version: 2.1
jobs:
  build:
    docker:
      - image: ruby:3.0.2
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: apt update && apt install -y cmake pkg-config
      - run:
          name: Run the default task
          command: |
            gem install bundler -v 2.3.4
            bundle install
            bundle exec rake
